TEST_CASES = [
    # --- BASIC RETRIEVAL (1-40) ---
    ("show all students", "SELECT * FROM students;", "Basic Retrieval", "Easy"),
    ("get all employees", "SELECT * FROM employees;", "Basic Retrieval", "Easy"),
    ("display all products", "SELECT * FROM products;", "Basic Retrieval", "Easy"),
    ("list all customers", "SELECT * FROM customers;", "Basic Retrieval", "Easy"),
    ("show all departments", "SELECT * FROM departments;", "Basic Retrieval", "Easy"),
    ("get all courses", "SELECT * FROM courses;", "Basic Retrieval", "Easy"),
    ("all students", "SELECT * FROM students;", "Basic Retrieval", "Easy"),
    ("list reviews", "SELECT * FROM reviews;", "Basic Retrieval", "Easy"),
    ("show all cars", "SELECT * FROM cars;", "Basic Retrieval", "Easy"),
    ("fetch all projects", "SELECT * FROM projects;", "Basic Retrieval", "Easy"),
    ("get all suppliers", "SELECT * FROM suppliers;", "Basic Retrieval", "Easy"),
    ("display all orders", "SELECT * FROM orders;", "Basic Retrieval", "Easy"),
    ("show all categories", "SELECT * FROM categories;", "Basic Retrieval", "Easy"),
    ("all books", "SELECT * FROM books;", "Basic Retrieval", "Easy"),
    ("get all professors", "SELECT * FROM professors;", "Basic Retrieval", "Easy"),
    ("list all team members", "SELECT * FROM employees;", "Basic Retrieval", "Easy"),
    ("all items", "SELECT * FROM products;", "Basic Retrieval", "Easy"),
    ("show all transactions", "SELECT * FROM transactions;", "Basic Retrieval", "Easy"),
    ("list all users", "SELECT * FROM users;", "Basic Retrieval", "Easy"),
    ("get all enrollments", "SELECT * FROM enrollments;", "Basic Retrieval", "Easy"),
    ("show all brands", "SELECT * FROM brands;", "Basic Retrieval", "Easy"),
    ("all office locations", "SELECT * FROM locations;", "Basic Retrieval", "Easy"),
    ("list all sales", "SELECT * FROM sales;", "Basic Retrieval", "Easy"),
    ("get all models", "SELECT * FROM models;", "Basic Retrieval", "Easy"),
    ("show all inventory", "SELECT * FROM products;", "Basic Retrieval", "Easy"),
    ("all personnel", "SELECT * FROM employees;", "Basic Retrieval", "Easy"),
    ("list all divisions", "SELECT * FROM departments;", "Basic Retrieval", "Easy"),
    ("fetch all items", "SELECT * FROM items;", "Basic Retrieval", "Easy"),
    ("all active students", "SELECT * FROM students WHERE is_active = true;", "Basic Retrieval", "Easy"),
    ("get all available cars", "SELECT * FROM cars WHERE is_available = true;", "Basic Retrieval", "Easy"),
    ("show all manufacturers", "SELECT * FROM suppliers;", "Basic Retrieval", "Easy"),
    ("list all faculty", "SELECT * FROM employees WHERE position = 'Faculty';", "Basic Retrieval", "Easy"),
    ("all electronics", "SELECT * FROM products WHERE category = 'Electronics';", "Basic Retrieval", "Easy"),
    ("get all branches", "SELECT * FROM departments;", "Basic Retrieval", "Easy"),
    ("show all vehicles", "SELECT * FROM cars;", "Basic Retrieval", "Easy"),
    ("list all stock", "SELECT * FROM products;", "Basic Retrieval", "Easy"),
    ("all client records", "SELECT * FROM customers;", "Basic Retrieval", "Easy"),
    ("fetch all staff", "SELECT * FROM employees;", "Basic Retrieval", "Easy"),
    ("show all records from students", "SELECT * FROM students;", "Basic Retrieval", "Easy"),
    ("display all employee data", "SELECT * FROM employees;", "Basic Retrieval", "Easy"),

    # --- FILTERING - EQUALS & COMPARISON (41-90) ---
    ("students in IT department", "SELECT * FROM students WHERE department = 'IT';", "Filtering", "Medium"),
    ("products in Electronics category", "SELECT * FROM products WHERE category = 'Electronics';", "Filtering", "Medium"),
    ("students in year 2023", "SELECT * FROM students WHERE year = 2023;", "Filtering", "Medium"),
    ("products in stock", "SELECT * FROM products WHERE in_stock = true;", "Filtering", "Medium"),
    ("students with cgpa greater than 3.5", "SELECT * FROM students WHERE cgpa > 3.5;", "Filtering", "Medium"),
    ("employees with salary > 50000", "SELECT * FROM employees WHERE salary > 50000;", "Filtering", "Medium"),
    ("products with rating less than 3", "SELECT * FROM products WHERE rating < 3;", "Filtering", "Medium"),
    ("students with age > 20", "SELECT * FROM students WHERE age > 20;", "Filtering", "Medium"),
    ("cars with price > 20000", "SELECT * FROM cars WHERE price > 20000;", "Filtering", "Medium"),
    ("projects with budget > 100000", "SELECT * FROM projects WHERE budget > 100000;", "Filtering", "Medium"),
    ("employees in HR position", "SELECT * FROM employees WHERE position = 'HR';", "Filtering", "Medium"),
    ("cars from brand BMW", "SELECT * FROM cars WHERE brand = 'BMW';", "Filtering", "Medium"),
    ("orders with total amount > 500", "SELECT * FROM orders WHERE total_amount > 500;", "Filtering", "Medium"),
    ("products with discount > 10", "SELECT * FROM products WHERE discount_percentage > 10;", "Filtering", "Medium"),
    ("customers in city Mumbai", "SELECT * FROM customers WHERE city = 'Mumbai';", "Filtering", "Medium"),
    ("students with marks > 80", "SELECT * FROM students WHERE marks > 80;", "Filtering", "Medium"),
    ("projects in status completed", "SELECT * FROM projects WHERE status = 'completed';", "Filtering", "Medium"),
    ("employees with experience > 5", "SELECT * FROM employees WHERE experience_years > 5;", "Filtering", "Medium"),
    ("cars with mileage > 15", "SELECT * FROM cars WHERE mileage > 15;", "Filtering", "Medium"),
    ("products with stock < 50", "SELECT * FROM products WHERE stock < 50;", "Filtering", "Medium"),
    ("students with semester 5", "SELECT * FROM students WHERE semester = 5;", "Filtering", "Medium"),
    ("suppliers with rating > 4", "SELECT * FROM suppliers WHERE rating > 4;", "Filtering", "Medium"),
    ("employees with level 3", "SELECT * FROM employees WHERE level = 3;", "Filtering", "Medium"),
    ("cars with year 2022", "SELECT * FROM cars WHERE year = 2022;", "Filtering", "Medium"),
    ("projects with priority high", "SELECT * FROM projects WHERE priority = 'high';", "Filtering", "Medium"),
    ("students with gpa < 2.0", "SELECT * FROM students WHERE gpa < 2.0;", "Filtering", "Medium"),
    ("orders with status pending", "SELECT * FROM orders WHERE status = 'pending';", "Filtering", "Medium"),
    ("employees from USA", "SELECT * FROM employees WHERE country = 'USA';", "Filtering", "Medium"),
    ("products with weight > 5", "SELECT * FROM products WHERE weight > 5;", "Filtering", "Medium"),
    ("courses with credits 4", "SELECT * FROM courses WHERE credits = 4;", "Filtering", "Medium"),
    ("suppliers from country UK", "SELECT * FROM suppliers WHERE country = 'UK';", "Filtering", "Medium"),
    ("employees with bonus > 5000", "SELECT * FROM employees WHERE bonus > 5000;", "Filtering", "Medium"),
    ("students from city Delhi", "SELECT * FROM students WHERE city = 'Delhi';", "Filtering", "Medium"),
    ("cars with horsepower > 150", "SELECT * FROM cars WHERE horsepower > 150;", "Filtering", "Medium"),
    ("orders for customer 105", "SELECT * FROM orders WHERE customer_id = 105;", "Filtering", "Medium"),
    ("products with subcategory laptop", "SELECT * FROM products WHERE subcategory = 'laptop';", "Filtering", "Medium"),
    ("employees with gender male", "SELECT * FROM employees WHERE gender = 'male';", "Filtering", "Medium"),
    ("students with scholarship > 1000", "SELECT * FROM students WHERE scholarship_amount > 1000;", "Filtering", "Medium"),
    ("projects with team size > 10", "SELECT * FROM projects WHERE team_size > 10;", "Filtering", "Medium"),
    ("cars with fuel type petrol", "SELECT * FROM cars WHERE fuel_type = 'petrol';", "Filtering", "Medium"),
    ("products from brand Apple", "SELECT * FROM products WHERE brand = 'Apple';", "Filtering", "Medium"),
    ("employees with age < 30", "SELECT * FROM employees WHERE age < 30;", "Filtering", "Medium"),
    ("students with year joined 2021", "SELECT * FROM students WHERE year = 2021;", "Filtering", "Medium"),
    ("suppliers in city New York", "SELECT * FROM suppliers WHERE city = 'New York';", "Filtering", "Medium"),
    ("orders with is_paid true", "SELECT * FROM orders WHERE is_paid = true;", "Filtering", "Medium"),
    ("products in warehouse A", "SELECT * FROM products WHERE warehouse_location = 'A';", "Filtering", "Medium"),
    ("employees with experience years < 2", "SELECT * FROM employees WHERE experience_years < 2;", "Filtering", "Medium"),
    ("cars with rating > 4.5", "SELECT * FROM cars WHERE rating > 4.5;", "Filtering", "Medium"),
    ("students in major Computer Science", "SELECT * FROM students WHERE major = 'Computer Science';", "Filtering", "Medium"),
    ("projects with spent amount < 5000", "SELECT * FROM projects WHERE spent_amount < 5000;", "Filtering", "Medium"),

    # --- LIKE, IN, BETWEEN (91-120) ---
    ("students with name like John", "SELECT * FROM students WHERE name LIKE '%John%';", "Filtering", "Hard"),
    ("products with name like Phone", "SELECT * FROM products WHERE name LIKE '%Phone%';", "Filtering", "Hard"),
    ("students in year 2023, 2024", "SELECT * FROM students WHERE year IN (2023, 2024);", "Filtering", "Hard"),
    ("employees in department IT, HR", "SELECT * FROM employees WHERE department IN ('IT', 'HR');", "Filtering", "Hard"),
    ("products with price between 100 and 500", "SELECT * FROM products WHERE price BETWEEN 100 AND 500;", "Filtering", "Hard"),
    ("students with cgpa between 3.0 and 4.0", "SELECT * FROM students WHERE cgpa BETWEEN 3.0 AND 4.0;", "Filtering", "Hard"),
    ("employees with name like Smith", "SELECT * FROM employees WHERE name LIKE '%Smith%';", "Filtering", "Hard"),
    ("cars from brand BMW, Audi, Toyota", "SELECT * FROM cars WHERE brand IN ('BMW', 'Audi', 'Toyota');", "Filtering", "Hard"),
    ("projects with budget between 50000 and 200000", "SELECT * FROM projects WHERE budget BETWEEN 50000 AND 200000;", "Filtering", "Hard"),
    ("students with name containing Alex", "SELECT * FROM students WHERE name LIKE '%Alex%';", "Filtering", "Hard"),
    ("products with category Food, Drink", "SELECT * FROM products WHERE category IN ('Food', 'Drink');", "Filtering", "Hard"),
    ("employees with salary between 40000 and 80000", "SELECT * FROM employees WHERE salary BETWEEN 40000 AND 80000;", "Filtering", "Hard"),
    ("cars with model like SUV", "SELECT * FROM cars WHERE model LIKE '%SUV%';", "Filtering", "Hard"),
    ("suppliers in country India, USA", "SELECT * FROM suppliers WHERE country IN ('India', 'USA');", "Filtering", "Hard"),
    ("orders with amount between 200 and 1000", "SELECT * FROM orders WHERE total_amount BETWEEN 200 AND 1000;", "Filtering", "Hard"),
    ("students with major like Engineering", "SELECT * FROM students WHERE major LIKE '%Engineering%';", "Filtering", "Hard"),
    ("employees in position Manager, Director", "SELECT * FROM employees WHERE position IN ('Manager', 'Director');", "Filtering", "Hard"),
    ("products with rating between 4 and 5", "SELECT * FROM products WHERE rating BETWEEN 4 AND 5;", "Filtering", "Hard"),
    ("customers with city like San", "SELECT * FROM customers WHERE city LIKE '%San%';", "Filtering", "Hard"),
    ("students in semester 3, 4, 5", "SELECT * FROM students WHERE semester IN (3, 4, 5);", "Filtering", "Hard"),
    ("cars with mileage between 10 and 20", "SELECT * FROM cars WHERE mileage BETWEEN 10 AND 20;", "Filtering", "Hard"),
    ("employees in country Canada, UK", "SELECT * FROM employees WHERE country IN ('Canada', 'UK');", "Filtering", "Hard"),
    ("projects with spent between 1000 and 10000", "SELECT * FROM projects WHERE spent_amount BETWEEN 1000 AND 10000;", "Filtering", "Hard"),
    ("students with email like gmail", "SELECT * FROM students WHERE email LIKE '%gmail%';", "Filtering", "Hard"),
    ("products with brand Samsung, LG", "SELECT * FROM products WHERE brand IN ('Samsung', 'LG');", "Filtering", "Hard"),
    ("employees with age between 25 and 45", "SELECT * FROM employees WHERE age BETWEEN 25 AND 45;", "Filtering", "Hard"),
    ("cars with color red, blue", "SELECT * FROM cars WHERE color IN ('red', 'blue');", "Filtering", "Hard"),
    ("suppliers with rating between 3 and 5", "SELECT * FROM suppliers WHERE rating BETWEEN 3 AND 5;", "Filtering", "Hard"),
    ("orders with customer_id in 101, 102, 103", "SELECT * FROM orders WHERE customer_id IN (101, 102, 103);", "Filtering", "Hard"),
    ("products with stock between 10 and 100", "SELECT * FROM products WHERE stock BETWEEN 10 AND 100;", "Filtering", "Hard"),

    # --- RANKING (121-150) ---
    ("top 10 students with highest cgpa", "SELECT * FROM students ORDER BY cgpa DESC LIMIT 10;", "Ranking", "Medium"),
    ("top 5 employees with highest salary", "SELECT * FROM employees ORDER BY salary DESC LIMIT 5;", "Ranking", "Medium"),
    ("top 5 products by rating", "SELECT * FROM products ORDER BY rating DESC LIMIT 5;", "Ranking", "Medium"),
    ("bottom 5 students with lowest cgpa", "SELECT * FROM students ORDER BY cgpa ASC LIMIT 5;", "Ranking", "Medium"),
    ("cheapest 10 products", "SELECT * FROM products ORDER BY price ASC LIMIT 10;", "Ranking", "Medium"),
    ("first 5 students with highest cgpa", "SELECT * FROM students ORDER BY cgpa DESC LIMIT 5;", "Ranking", "Medium"),
    ("top 3 cars with highest price", "SELECT * FROM cars ORDER BY price DESC LIMIT 3;", "Ranking", "Medium"),
    ("top 20 employees by rating", "SELECT * FROM employees ORDER BY rating DESC LIMIT 20;", "Ranking", "Medium"),
    ("bottom 10 projects by completion", "SELECT * FROM projects ORDER BY completion_percentage ASC LIMIT 10;", "Ranking", "Medium"),
    ("best 15 cars by mileage", "SELECT * FROM cars ORDER BY mileage DESC LIMIT 15;", "Ranking", "Medium"),
    ("top 5 suppliers by rating", "SELECT * FROM suppliers ORDER BY rating DESC LIMIT 5;", "Ranking", "Medium"),
    ("bottom 3 students by marks", "SELECT * FROM students ORDER BY marks ASC LIMIT 3;", "Ranking", "Medium"),
    ("most expensive 5 products", "SELECT * FROM products ORDER BY price DESC LIMIT 5;", "Ranking", "Medium"),
    ("top 10 projects by budget", "SELECT * FROM projects ORDER BY budget DESC LIMIT 10;", "Ranking", "Medium"),
    ("lowest 5 salaries", "SELECT * FROM employees ORDER BY salary ASC LIMIT 5;", "Ranking", "Medium"),
    ("top 8 cars by sales", "SELECT * FROM cars ORDER BY units_sold DESC LIMIT 8;", "Ranking", "Medium"),
    ("worst 5 suppliers by rating", "SELECT * FROM suppliers ORDER BY rating ASC LIMIT 5;", "Ranking", "Medium"),
    ("top 10 orders by amount", "SELECT * FROM orders ORDER BY total_amount DESC LIMIT 10;", "Ranking", "Medium"),
    ("top 5 students by scholarship", "SELECT * FROM students ORDER BY scholarship_amount DESC LIMIT 5;", "Ranking", "Medium"),
    ("bottom 5 products by stock", "SELECT * FROM products ORDER BY stock ASC LIMIT 5;", "Ranking", "Medium"),
    ("top 3 employees by experience", "SELECT * FROM employees ORDER BY experience_years DESC LIMIT 3;", "Ranking", "Medium"),
    ("bottom 10 cars by horsepower", "SELECT * FROM cars ORDER BY horsepower ASC LIMIT 10;", "Ranking", "Medium"),
    ("top 5 projects by team size", "SELECT * FROM projects ORDER BY team_size DESC LIMIT 5;", "Ranking", "Medium"),
    ("best 10 products by discount", "SELECT * FROM products ORDER BY discount_percentage DESC LIMIT 10;", "Ranking", "Medium"),
    ("top 5 customers by spent", "SELECT * FROM customers ORDER BY total_spent DESC LIMIT 5;", "Ranking", "Medium"),
    ("bottom 3 students by age", "SELECT * FROM students ORDER BY age ASC LIMIT 3;", "Ranking", "Medium"),
    ("top 7 employees by bonus", "SELECT * FROM employees ORDER BY bonus DESC LIMIT 7;", "Ranking", "Medium"),
    ("top 10 cars by units sold", "SELECT * FROM cars ORDER BY units_sold DESC LIMIT 10;", "Ranking", "Medium"),
    ("bottom 5 suppliers by orders", "SELECT * FROM suppliers ORDER BY total_orders ASC LIMIT 5;", "Ranking", "Medium"),
    ("top 15 products by quantity", "SELECT * FROM products ORDER BY quantity DESC LIMIT 15;", "Ranking", "Medium"),

    # --- AGGREGATION (151-185) ---
    ("count of students", "SELECT COUNT(*) FROM students;", "Aggregation", "Medium"),
    ("how many employees", "SELECT COUNT(*) FROM employees;", "Aggregation", "Medium"),
    ("average salary of employees", "SELECT AVG(salary) FROM employees;", "Aggregation", "Medium"),
    ("average price of products", "SELECT AVG(price) FROM products;", "Aggregation", "Medium"),
    ("total salary of employees", "SELECT SUM(salary) FROM employees;", "Aggregation", "Medium"),
    ("maximum cgpa of students", "SELECT MAX(cgpa) FROM students;", "Aggregation", "Medium"),
    ("lowest price of products", "SELECT MIN(price) FROM products;", "Aggregation", "Medium"),
    ("count of cars", "SELECT COUNT(*) FROM cars;", "Aggregation", "Medium"),
    ("total budget of projects", "SELECT SUM(budget) FROM projects;", "Aggregation", "Medium"),
    ("how many orders", "SELECT COUNT(*) FROM orders;", "Aggregation", "Medium"),
    ("average rating of cars", "SELECT AVG(rating) FROM cars;", "Aggregation", "Medium"),
    ("max price of cars", "SELECT MAX(price) FROM cars;", "Aggregation", "Medium"),
    ("min mileage of cars", "SELECT MIN(mileage) FROM cars;", "Aggregation", "Medium"),
    ("sum of marks for students", "SELECT SUM(marks) FROM students;", "Aggregation", "Medium"),
    ("average attendance of students", "SELECT AVG(attendance_percentage) FROM students;", "Aggregation", "Medium"),
    ("total spent by customers", "SELECT SUM(total_spent) FROM customers;", "Aggregation", "Medium"),
    ("count of departments", "SELECT COUNT(*) FROM departments;", "Aggregation", "Medium"),
    ("max budget of departments", "SELECT MAX(budget) FROM departments;", "Aggregation", "Medium"),
    ("average experience of employees", "SELECT AVG(experience_years) FROM employees;", "Aggregation", "Medium"),
    ("total units sold of cars", "SELECT SUM(units_sold) FROM cars;", "Aggregation", "Medium"),
    ("count of projects", "SELECT COUNT(*) FROM projects;", "Aggregation", "Medium"),
    ("average completion of projects", "SELECT AVG(completion_percentage) FROM projects;", "Aggregation", "Medium"),
    ("min budget of projects", "SELECT MIN(budget) FROM projects;", "Aggregation", "Medium"),
    ("total scholarship amount", "SELECT SUM(scholarship_amount) FROM students;", "Aggregation", "Medium"),
    ("max rating of employees", "SELECT MAX(rating) FROM employees;", "Aggregation", "Medium"),
    ("count of courses", "SELECT COUNT(*) FROM courses;", "Aggregation", "Medium"),
    ("total credits of courses", "SELECT SUM(credits) FROM courses;", "Aggregation", "Medium"),
    ("average budget of departments", "SELECT AVG(budget) FROM departments;", "Aggregation", "Medium"),
    ("how many suppliers", "SELECT COUNT(*) FROM suppliers;", "Aggregation", "Medium"),
    ("total order value of suppliers", "SELECT SUM(total_value) FROM suppliers;", "Aggregation", "Medium"),
    ("max horsepower of cars", "SELECT MAX(horsepower) FROM cars;", "Aggregation", "Medium"),
    ("average age of employees", "SELECT AVG(age) FROM employees;", "Aggregation", "Medium"),
    ("sum of quantity in orders", "SELECT SUM(quantity) FROM orders;", "Aggregation", "Medium"),
    ("count of products in category", "SELECT COUNT(*) FROM products WHERE category = 'Electronics';", "Aggregation", "Medium"),
    ("average discount of products", "SELECT AVG(discount_percentage) FROM products;", "Aggregation", "Medium"),

    # --- COMPLEX - RANKING + FILTERING (186-195) ---
    ("top 10 students with highest cgpa in IT department", "SELECT * FROM students WHERE department = 'IT' ORDER BY cgpa DESC LIMIT 10;", "Complex Filtering + Ranking", "Hard"),
    ("top 5 employees with highest salary in HR department", "SELECT * FROM employees WHERE department = 'HR' ORDER BY salary DESC LIMIT 5;", "Complex Filtering + Ranking", "Hard"),
    ("top 10 products with highest price in Electronics category", "SELECT * FROM products WHERE category = 'Electronics' ORDER BY price DESC LIMIT 10;", "Complex Filtering + Ranking", "Hard"),
    ("top 5 students with highest marks in year 2023", "SELECT * FROM students WHERE year = 2023 ORDER BY marks DESC LIMIT 5;", "Complex Filtering + Ranking", "Hard"),
    ("bottom 5 students with lowest cgpa in CSE department", "SELECT * FROM students WHERE department = 'CSE' ORDER BY cgpa ASC LIMIT 5;", "Complex Filtering + Ranking", "Hard"),
    ("top 3 cars with highest price and brand BMW", "SELECT * FROM cars WHERE brand = 'BMW' ORDER BY price DESC LIMIT 3;", "Complex Filtering + Ranking", "Hard"),
    ("top 10 projects by budget in status active", "SELECT * FROM projects WHERE status = 'active' ORDER BY budget DESC LIMIT 10;", "Complex Filtering + Ranking", "Hard"),
    ("bottom 5 products by stock in warehouse A", "SELECT * FROM products WHERE warehouse_location = 'A' ORDER BY stock ASC LIMIT 5;", "Complex Filtering + Ranking", "Hard"),
    ("top 5 employees by bonus in level 3", "SELECT * FROM employees WHERE level = 3 ORDER BY bonus DESC LIMIT 5;", "Complex Filtering + Ranking", "Hard"),
    ("best 5 cars by mileage and year 2024", "SELECT * FROM cars WHERE year = 2024 ORDER BY mileage DESC LIMIT 5;", "Complex Filtering + Ranking", "Hard"),

    # --- COMPLEX - AGGREGATION + FILTERING (196-200) ---
    ("average salary of employees in IT department", "SELECT AVG(salary) FROM employees WHERE department = 'IT';", "Complex Filtering + Aggregation", "Hard"),
    ("average cgpa of students in CSE department", "SELECT AVG(cgpa) FROM students WHERE department = 'CSE';", "Complex Filtering + Aggregation", "Hard"),
    ("count of students in year 2023", "SELECT COUNT(*) FROM students WHERE year = 2023;", "Complex Filtering + Aggregation", "Hard"),
    ("total salary of employees in HR department", "SELECT SUM(salary) FROM employees WHERE department = 'HR';", "Complex Filtering + Aggregation", "Hard"),
    ("maximum price of products in Electronics category", "SELECT MAX(price) FROM products WHERE category = 'Electronics';", "Complex Filtering + Aggregation", "Hard"),
]